name: Run JOJ3 on Push
on: [push]

jobs:
  run:
    runs-on: focs-latest-slim
    container:
      volumes:
        - /home/tt/.config:/home/tt/.config
        - /home/tt/.cache:/home/tt/.cache
        - /home/tt/.ssh:/home/tt/.ssh
    steps:
      - name: Check out repository code
        uses: actions/checkout@focs
      - name: Fetch the submodule
        run: |
          git submodule update --init --recursive
      - name: Run joj3
        run: |
          sudo -E -u tt joj3 -conf-root /home/tt/.config/joj/projects/p2/push          

