#!/bin/bash

cd "$(dirname "$0")/.."
result=0
for file in $(find src -type f); do
  linec=$(wc -l < $file)
  [ $linec -ge 400 ] && echo "$file exceeds maximum filesize (400 lines)" && result=1
  [ $linec -ge 300 ] && [ $linec -lt 400 ] && echo "$file exceeds recommended filesize (300 lines)" && result=1
done
exit $result
